# try:
#     print(10/2)
# # except Exception as e:
# except ZeroDivisionError as e:
#     print(e)
# finally:
#     print("done")

# print("we are learning exception handling in python")


# def add(x,y):
#     if y==0:
#         raise Exception("zero pass garna mildaina")
#     return x+y


# try:
#     print(add(3,0))
# except Exception as e:
#     print(e)
